# -*- coding: utf-8 -*-
"""Roof plan comparison.ipynb

Automatically generated by Colab.

Original file is located at
    https://colab.research.google.com/drive/1j36mI7R-niiA70btL8eJ594-wPXg0XoS
"""

!apt-get install -y poppler-utils

!pip install pdf2image

!pip install opencv-python

import cv2
import numpy as np
from matplotlib import pyplot as plt
from pdf2image import convert_from_path

def extract_and_split_pdf(pdf_path):
    pages = convert_from_path(pdf_path, dpi=300)
    if len(pages) > 1:
        raise ValueError("The PDF contains multiple pages. Ensure only one page is provided.")

    pdf_image = np.array(pages[0])
    pdf_image = cv2.cvtColor(pdf_image, cv2.COLOR_RGB2BGR)

    height, width, _ = pdf_image.shape
    mid_width = width // 2
    existing_plan = pdf_image[:, :mid_width]
    proposed_plan = pdf_image[:, mid_width:]

    return existing_plan, proposed_plan

def preprocess_image(image):
    gray_image = cv2.cvtColor(image, cv2.COLOR_BGR2GRAY)
    resized_image = cv2.resize(gray_image, (1024, 1024))
    normalized_image = cv2.equalizeHist(resized_image)
    return normalized_image

def segment_floor_plan(image):
    _, segmented = cv2.threshold(image, 127, 255, cv2.THRESH_BINARY)
    return segmented

def compare_images(image1, image2):
    difference = cv2.absdiff(image1, image2)
    _, diff_thresh = cv2.threshold(difference, 30, 255, cv2.THRESH_BINARY)
    return diff_thresh

def main(pdf_path):
    existing_plan, proposed_plan = extract_and_split_pdf(pdf_path)

    existing_image = preprocess_image(existing_plan)
    proposed_image = preprocess_image(proposed_plan)

    existing_segmented = segment_floor_plan(existing_image)
    proposed_segmented = segment_floor_plan(proposed_image)


    difference = compare_images(existing_segmented, proposed_segmented)


    plt.figure(figsize=(15, 10))
    plt.subplot(1, 3, 1)
    plt.title("Existing Plan")
    plt.imshow(existing_segmented, cmap='gray')
    plt.subplot(1, 3, 2)
    plt.title("Proposed Plan")
    plt.imshow(proposed_segmented, cmap='gray')
    plt.subplot(1, 3, 3)
    plt.title("Differences")
    plt.imshow(difference, cmap='gray')
    plt.show()


pdf_path = "/content/Proposed and Existing Roof Plan.pdf"
main(pdf_path)

